---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-app-hardened-redis
  labels:
    app: k8s-node-app-hardened-redis
spec:
  selector:
    matchLabels:
      app: k8s-node-app-hardened-redis
  template:
    metadata:
      labels:
        app: k8s-node-app-hardened-redis
    spec:
      containers:
        - name: redis
          image: redis:4.0-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-node-app-hardened-redis
  labels:
    app: k8s-node-app-hardened-redis
spec:
  ports:
    - name: redis-16379
      port: 16379
      targetPort: 6379
  selector:
    app: k8s-node-app-hardened-redis
